### ISSUE TITLE
Server returns improper numeric for Enforced nicks

### ISSUE THREAD

**Issue by jfcantu** [DALnet/bahamut#109]
Whenever a user connects and their nick is being held by Services, the server responds with numeric 432 ("Erroneous Nickname") rather than numeric 433 ("Nickname In Use.") 

This causes problems on some IRC clients because 432 doesn't trigger the client to try switching to an alternate nick, like 433 does. On Limechat, this causes the client to ignore the message and wait for a response until the connection times out, while IRSSI will disconnect immediately.

**Comment by jfcantu** [comment]
https://github.com/DALnet/bahamut/blob/688ef22d2ec4fe6bfd9cad798ba384620aed5c0a/src/m_nick.c#L621-L639

TL;DR, Bahamut doesn't distinguish between Enforcer SQLINEs and normal SQLINEs, so it always returns 432.

**Comment by kobishmueli** [comment]
Sounds like a client bug and not a bahamut bug, the nick is not in-use but (temporary) forbidden to use.

Kobi.

**Comment by jfcantu** [comment]
That's fair... I guess it's kind of a philosophical question about which numeric better meets the intent of a services hold, since the RFC doesn't specify.

(FWIW, I checked and found Inspircd/Anope do the same thing.)
