### ISSUE TITLE
no ./configure file

### ISSUE THREAD

**Issue by NightcoreSergeant** [DALnet/bahamut#114]
Please update INSTALL

**Comment by netfw** [comment]
Please compile to include/setup.h and use configure.in file (make).

**Comment by charpour** [comment]
I'm not sure I understand, how do you build it, could you please provide the steps?

If I do autoconf followed by automake, I'm getting an error (configure.in: error: no proper invocation of AM_INIT_AUTOMAKE was found.)

**Comment by kobishmueli** [comment]
INSTALL is really there for the official tarballs that include the configure script (https://www.dal.net/?page=Bahamut)

Please see https://github.com/DALnet/bahamut/wiki for the instructions on how to install it from the GitHub repository. I'll see about adding it to the INSTALL file later.

**Comment by charpour** [comment]
Sure, thank you for this information.
