### ISSUE TITLE
Possible oper block corruption when two opers share the same IP address

### ISSUE THREAD

**Issue by rscs** [DALnet/bahamut#180]
Hidden- and his bopm share the same IP address.  He's seeing problems where the bopm cannot oper due to a bad password.

There may be some corruption or a problem with the logic when opers share a similar oper block.

See the full details on the coders@ thread.

**Comment by crigler** [comment]
The logic for CIDR O:lines in `s_conf.c:find_oper` is broken. It looks like the first oper block that has a matching CIDR host will win, even if the oper's nick does not match.
