### ISSUE TITLE
Malformed response to CONNECT on local server

### ISSUE THREAD

**Issue by arfNZ** [DALnet/bahamut#190]
When attempting to connect to a server without a connect block the response message is missing the source :server:
```
>> /CONNECT invalidserver.* 7325
<< NOTICE Arfie :Connect: No Connect block found for invalidserver.*.
```
On a remote server it works ok:
```
>> /CONNECT invalidserver.* 7325 midnight.*
<< :midnight.hub.dal.net NOTICE Arfie :Connect: No Connect block found for invalidserver.*.
```
Both znc and my client handle the message ok - but if I'm parsing the message to determine the origin, it's simply not there.

**Comment by kobishmueli** [comment]
Arfie: Thanks for letting us know, pull request #191 should fix this.

Kobi.

**Comment by eaescob** [comment]
PR Merged
