### ISSUE TITLE
I want to install bahamut

### ISSUE THREAD

**Issue by fahadmehar** [DALnet/bahamut#21]
I need the full guide how to install bahamut? shall i install in "root" ?

**Comment by jbaez001** [comment]
Hey @fahadmehar, read through the "INSTALL" file. The "doc" folder contains some general documentation as well. Also, you don't really want to install an IRCD as root or run it as root; it should be under a regular account. 

In actuality, you really want to be careful as to what processes you run as root. That in and out of itself, is a whole different discussion subject not really pertaining to bahamut, but more along the lines of security concerns.

**Comment by fahadmehar** [comment]
@jbaez001 I have seen that, It's only saying "./configure" thing? It's not step by step.
How I unzip file in account ? I don't see any help there.

**Comment by mueddib** [comment]
Hello @fahadmehar I don't think it will be difficul install bahamut. you will first run ./configure command then run .config command and this command created with config file (check to all config files) and run make and make install commands installed with bahamut.

**Comment by fahadmehar** [comment]
@mueddib OK I will run ./configure then other as you mention.  But 1st I have to unzip bahamut-2.0.7.tar in account right? How I do ?  After I unzip then I will ./configure and so on.

**Comment by dorklord23** [comment]
@fahadmehar, what OS do you use, actually? I don't think you should've had any problem with unzipping.

**Comment by fahadmehar** [comment]
@dorklord23 I use Windows 10 Creative - I am new at server adding i need the commands.

**Comment by akalsnes** [comment]
It may be worthwhile to include steps to actually produce the "configure" file. These steps from the wiki helped me greatly:

```
libtoolize -c --force
aclocal
autoheader
automake -c --force-missing --add-missing
autoconf
./configure
make
make install
```

I do not believe I would have been able to figure out how to produce the configure file without that information.
