### ISSUE TITLE
Configuring Bahamut

### ISSUE THREAD

**Issue by dorklord23** [DALnet/bahamut#22]
Hi :)

I've installed Bahamut in my local computer (Ubuntu 17.04). In such case, what name should I use in `global` block?

    global {
        name    irc.example.com;         # I use this name in localhost
        info    "IRC SIMPEG";     # A short info line
        admin {
            "IRC untuk SIMPEG";   # Three information lines sent
            "Admin SIMPEG"; # in reply to ADMIN command
            "adminsimpeg@example.com";
        };
    };

I use `irc.example.com` because using `localhost` would trigger an error.

**Comment by GLolol** [comment]
There's no specific name that you must use since the IRCd instance is yours to play with. However, a server name must have a `.` in it, so perhaps something like `bahamut.local` or `localhost.localdomain` would work.
