### ISSUE TITLE
Compilation error on debian 12 [...] undefined « __dn_expand »

### ISSUE THREAD

**Issue by dktmb** [DALnet/bahamut#237]
Hi there,

Have seen #218 but I'm not able to understand what I have to do to fix this issue.
After ./configure, make returns these errors : 

/home/ltef/IRC/bahamut-2.1.5/src/res.c:622 : undefined reference « __res_mkquery »
/usr/bin/ld : res.o : in function « proc_answer » :
/home/ltef/IRC/bahamut-2.1.5/src/res.c:870 :undefined reference to « __dn_expand »
/usr/bin/ld : /home/ltef/IRC/bahamut-2.1.5/src/res.c:968 : undefined reference to « __dn_expand »
/usr/bin/ld : /home/ltef/IRC/bahamut-2.1.5/src/res.c:1138 : undefined reference to « __dn_expand »
/usr/bin/ld : /home/ltef/IRC/bahamut-2.1.5/src/res.c:1270 : undefined reference to « __dn_expand »

Any suggestion will be appreciated !
Thanks,

**Comment by eaescob** [comment]
Weird. I can combile main on Ubuntu 23 with no issues. Let me try with Ubuntu 22.

**Comment by eaescob** [comment]
Valid. I'll cut a new release that fixes this.

**Comment by eaescob** [comment]
But PR #219 fixes this
