### ISSUE TITLE
/stats P behavior

### ISSUE THREAD

**Issue by bclaghorn** [DALnet/bahamut#38]
Having experience with both ircd-ratbox and ircd-hybrid I note and use the /stats P functionality, which, to my knowledge, is absent for some reason in Bahamut. In both ircd-ratbox and ircd-hybrid, the /stats P (note uppercase, not lowercase) denotes a list of listen {} blocks, or ports 6660-6669, etc. Whether this is buried and disabled but present within the current Bahamut code somewhere (possible, as /stats P or p displays opers regardless of capitalization), or has been striped at some point I'd like to request the feature be re/added back with the upcoming changes if at all possible.

+ opers.txt
+ stats * P - Shows configured listen {} blocks
+ stats   p - Shows opers connected and their idle times

Example output from ratbox on /stats P

P 6697 irc.somebox.net 34 active ssl
P 7000 irc.somebox.net 24 active ssl
P 6667 irc.somebox.net 206 active
P 6660 irc.somebox.net 0 active
P 6661 irc.somebox.net 0 active
P 6662 irc.somebox.net 0 active
P 6663 irc.somebox.net 0 active
P 6664 irc.somebox.net 0 active
P 6665 irc.somebox.net 0 active
P 6667 irc.somebox.net 78 active

Thanks for your consideration!

**Comment by rscs** [comment]
Speaking with brandon and we do feel this is a missing feature.  I would not use /stats P though as this may break things that already depend on it.  Looks like we have the letters b, e, f, h, j, and x available.

The output will be the port, bind IP, ipmask, and flags, BUT the bind IP and ipmask should be masked with "*" in the same way that we do for /stats c.  We can just copy that same code with the "if(IsULine(sptr) || (MyClient(sptr) && IsAdmin(sptr)))" guard.

**Comment by rscs** [comment]
After talking with @eaescob, let's go with /stats P after all :)
